version: '2'
services:
  php:
    image: php:7.3.2-fpm
    volumes:
     - D:\swoole\nginx_php\html:/usr/share/nginx/html
    networks:
     app_net:
      ipv4_address: 10.10.10.1
  web:
      image: nginx/php:0.0.1
      links:
       - php
      ports:
       - "8889:80"
      working_dir: /usr/share/nginx/html
      volumes:
       - D:\swoole\nginx_php\html:/usr/share/nginx/html
      networks:
        - app_net
networks:
    # 配置docker network
    app_net:
        driver: bridge
        ipam:
            config:
                # 子网络
                - subnet: 10.10.0.0/16
#docker cp ./default.conf  nginx_php_web_1:/etc/nginx/conf.d/default.conf